apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-recovery
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "delete"]
